{% set version = "1.5.7" %}

package:
  name: ps2ff
  version: {{ version }}

source:
  url: https://code.usgs.gov/ghsc/esi/ps2ff/-/archive/v{{ version }}/ps2ff-v{{ version }}.tar.gz
  sha256: a02f95117b12ad230a7f26a9bd7455602f786b008b50dd21507d5bba07ef55b2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy
    - pandas
    - configobj

test:

  imports:
    - ps2ff

about:
  home: https://code.usgs.gov/ghsc/esi/ps2ff
  license: CC-PDDC
  summary: 'Produce approximated earthquake rupture distances from point source information.'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - emthompson-usgs
    - cbworden
