{% set name = "ps2ff" %}
{% set version = "1.5.8" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ps2ff-{{ version }}.tar.gz
  sha256: 183321e29708ed3e9ebee95247c3c676a3d8f6ff5d4d9f1ae9a79629ab3e8018

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  entry_points:
    - run_ps2ff = ps2ff.bin.run_ps2ff:cli
    - run_ps2ff_single_event = ps2ff.bin.run_ps2ff_single_event:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy>=1.21,<2.0
    - scipy>=1.7
    - pandas>=1.0
    - configobj>=5.0.6

test:
  requires:
    - python {{ python_min }}
  imports:
    - ps2ff
  commands:
    - run_ps2ff --help
    - run_ps2ff_single_event --help

about:
  home: https://code.usgs.gov/ghsc/esi/ps2ff
  license: LicenseRef-PublicDomain
  summary: 'Produce approximated earthquake rupture distances from point source information.'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - emthompson-usgs
    - cbworden
    - ocefpaf
